version: 2.0.{build}
platform: x64
clone_folder: c:\building\src\github.com\kelindar\etop

environment:  
  GOPATH: c:\gopath

install:  
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.11.2.windows-amd64.zip
  - 7z x go1.11.2.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go mod download

build_script:
- cmd: .\build.bat

artifacts:  
  - path: build/*
    name: binary

deploy:
  - provider: GitHub
    auth_token:
      secure: ImwOgsH/e1F+reDfqNIvoQ773FZHsjQt/4znrFdxUVrs1VNpFK9IUaW4hIL/yl4c
    release: 'v$(appveyor_build_version)'
    description: 'Build of Emitter Top Utility v$(appveyor_build_version).'
    draft: true
    prerelease: true
    artifact: binary